# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: |
    echo Setting up git credentials...
    git config user.email "prog.lope@gmail.com"
    git config user.name "prolopez"

- script: |
    echo Synchronizing changes to Azure Repos...
    git remote add azure https://tuorganizacion@dev.azure.com/tuorganizacion/tuproyecto/_git/turepositorio
    git push azure HEAD:refs/heads/master
  displayName: 'Synchronize changes to Azure Repos'
  
- script: echo Synchronization completed successfully!
  displayName: 'Completion Message'
