trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: |
    echo Setting up git credentials...
    git config user.email "prog.lopez@gmail.com"
    git config user.name "proglopez"

- script: |
    echo Synchronizing changes to Azure Repos...
    git remote add azure https://edwarddevopsapp@dev.azure.com/edwarddevopsapp/AppDevops/_git/AppDevops
    git push azure HEAD:refs/heads/master
  displayName: 'Synchronize changes to Azure Repos'
  
- script: echo Synchronization completed successfully!
  displayName: 'Completion Message'

