name: CI para Proyecto ApiCamisetas

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configuración de .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Construir proyecto
      run: dotnet build --no-restore

    - name: Publicar proyecto
      run: dotnet publish -c Release -o ./publish

    - name: Desplegar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_package
